## getting started with pandas

In [47]:
# pip install pandas #done

In [2]:
import pandas

In [5]:
import pandas

mydataset = {
    'cars':["BMW","volvo","Ford"],
    'passings':[3,7,2]
}

myvar =  pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  volvo         7
2   Ford         2

## checking pandas version

In [6]:
import pandas as pd

print(pd.__version__)

2.0.3

### What is a Series?

##### A Pandas Series is like a column in a table. It is a one-dimensional array holding data of any type.

In [9]:
import pandas as pd

x = [1,7,2]

myvar = pd.Series(x)

print(myvar)

0    1
1    7
2    2
dtype: int64

### Create Labels
With the index argument, you can name your own labels.

In [10]:
# we can replace above 0 1 2 serials with own numbering example :

import pandas as pd

x =[5,6,7]

myvar = pd.Series(x,index = ["x","y","z"])

print(myvar)

x    5
y    6
z    7
dtype: int64

In [11]:
print(myvar["y"])

6

## Key/Value Objects as Series

#### Note: The keys of the dictionary become the labels.

In [12]:
calories = {"day1": 420, "day2": 380, "day3": 390}

In [15]:
import pandas as pd

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

### if we add custom label of only day1 and day2 only data of day1 & day 2 will come and other remainig will vanish :

In [19]:
import pandas as pd

myvar = pd.Series(calories,index = ["day1","day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [20]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

In [21]:
import pandas as pd

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45

## Locate Row
As you can see from the result above, the DataFrame is like a table with rows and columns.
Pandas use the loc attribute to return one or more specified row(s)

In [26]:
#refer to the row index:
print(myvar.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

### here we located the row ZERO and python returned its values

In [25]:
#use a list of indexes:
print(myvar.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

In [28]:
# NOW lets add a custom index to data

myvar = pd.DataFrame(data,index=['day1','day2','day3'])

In [29]:
myvar

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [30]:
myvar.loc["day3"]

calories    390
duration     45
Name: day3, dtype: int64

# opening files in PANDAS

In [36]:
import pandas as pd

df = pd.read_csv("data.csv")

print(df) # df.to_string

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

### Tip: use to_string() to print the entire DataFrame.

# max_rows

pd.options.display.max_rows    

You can check your system's maximum rows with the pd.options.display.max_rows statement.

In [38]:
pd.options.display.max_rows

60

number is 60, which means that if the DataFrame contains more than 60 rows, the print(df) statement will return only the headers and the first and last 5 rows.

#### Increase the maximum number of rows to display the entire DataFrame:

In [43]:
pd.options.display.max_rows = 9999

df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

# Read JSON

In [44]:
import pandas as pd

df = pd.read_json("data.json")

In [46]:
df.to_string()

'     Duration  Pulse  Maxpulse  Calories\n0          60    110       130     409.1\n1          60    117       145     479.0\n2          60    103       135     340.0\n3          45    109       175     282.4\n4          45    117       148     406.0\n5          60    102       127     300.5\n6          60    110       136     374.0\n7          45    104       134     253.3\n8          30    109       133     195.1\n9          60     98       124     269.0\n10         60    103       147     329.3\n11         60    100       120     250.7\n12         60    106       128     345.3\n13         60    104       132     379.3\n14         60     98       123     275.0\n15         60     98       120     215.2\n16         60    100       120     300.0\n17         45     90       112       NaN\n18         60    103       123     323.0\n19         45     97       125     243.0\n20         60    108       131     364.2\n21         45    100       119     282.0\n22         60    130       101     300.0\n23         45    105       132     246.0\n24         60    102       126     334.5\n25         60    100       120     250.0\n26         60     92       118     241.0\n27         60    103       132       NaN\n28         60    100       132     280.0\n29         60    102       129     380.3\n30         60     92       115     243.0\n31         45     90       112     180.1\n32         60    101       124     299.0\n33         60     93       113     223.0\n34         60    107       136     361.0\n35         60    114       140     415.0\n36         60    102       127     300.5\n37         60    100       120     300.1\n38         60    100       120     300.0\n39         45    104       129     266.0\n40         45     90       112     180.1\n41         60     98       126     286.0\n42         60    100       122     329.4\n43         60    111       138     400.0\n44         60    111       131     397.0\n45         60     99       119     273.0\n46         60    109       153     387.6\n47         45    111       136     300.0\n48         45    108       129     298.0\n49         60    111       139     397.6\n50         60    107       136     380.2\n51         80    123       146     643.1\n52         60    106       130     263.0\n53         60    118       151     486.0\n54         30    136       175     238.0\n55         60    121       146     450.7\n56         60    118       121     413.0\n57         45    115       144     305.0\n58         20    153       172     226.4\n59         45    123       152     321.0\n60        210    108       160    1376.0\n61        160    110       137    1034.4\n62        160    109       135     853.0\n63         45    118       141     341.0\n64         20    110       130     131.4\n65        180     90       130     800.4\n66        150    105       135     873.4\n67        150    107       130     816.0\n68         20    106       136     110.4\n69        300    108       143    1500.2\n70        150     97       129    1115.0\n71         60    109       153     387.6\n72         90    100       127     700.0\n73        150     97       127     953.2\n74         45    114       146     304.0\n75         90     98       125     563.2\n76         45    105       134     251.0\n77         45    110       141     300.0\n78        120    100       130     500.4\n79        270    100       131    1729.0\n80         30    159       182     319.2\n81         45    149       169     344.0\n82         30    103       139     151.1\n83        120    100       130     500.0\n84         45    100       120     225.3\n85         30    151       170     300.1\n86         45    102       136     234.0\n87        120    100       157    1000.1\n88         45    129       103     242.0\n89         20     83       107      50.3\n90        180    101       127     600.1\n91         45    107       137       NaN\n92         30     90       107     105.3\n93         15     80       100      50.5\n94         20    150       171     127.4\n95         20    151       168     229.4\n96         30     95       128     128.2\n97         25    152       168     244.2\n98         30    109       131     188.2\n99         90     93       124     604.1\n100        20     95       112      77.7\n101        90     90       110     500.0\n102        90     90       100     500.0\n103        90     90       100     500.4\n104        30     92       108      92.7\n105        30     93       128     124.0\n106       180     90       120     800.3\n107        30     90       120      86.2\n108        90     90       120     500.3\n109       210    137       184    1860.4\n110        60    102       124     325.2\n111        45    107       124     275.0\n112        15    124       139     124.2\n113        45    100       120     225.3\n114        60    108       131     367.6\n115        60    108       151     351.7\n116        60    116       141     443.0\n117        60     97       122     277.4\n118        60    105       125       NaN\n119        60    103       124     332.7\n120        30    112       137     193.9\n121        45    100       120     100.7\n122        60    119       169     336.7\n123        60    107       127     344.9\n124        60    111       151     368.5\n125        60     98       122     271.0\n126        60     97       124     275.3\n127        60    109       127     382.0\n128        90     99       125     466.4\n129        60    114       151     384.0\n130        60    104       134     342.5\n131        60    107       138     357.5\n132        60    103       133     335.0\n133        60    106       132     327.5\n134        60    103       136     339.0\n135        20    136       156     189.0\n136        45    117       143     317.7\n137        45    115       137     318.0\n138        45    113       138     308.0\n139        20    141       162     222.4\n140        60    108       135     390.0\n141        60     97       127       NaN\n142        45    100       120     250.4\n143        45    122       149     335.4\n144        60    136       170     470.2\n145        45    106       126     270.8\n146        60    107       136     400.0\n147        60    112       146     361.9\n148        30    103       127     185.0\n149        60    110       150     409.4\n150        60    106       134     343.0\n151        60    109       129     353.2\n152        60    109       138     374.0\n153        30    150       167     275.8\n154        60    105       128     328.0\n155        60    111       151     368.5\n156        60     97       131     270.4\n157        60    100       120     270.4\n158        60    114       150     382.8\n159        30     80       120     240.9\n160        30     85       120     250.4\n161        45     90       130     260.4\n162        45     95       130     270.0\n163        45    100       140     280.9\n164        60    105       140     290.8\n165        60    110       145     300.4\n166        60    115       145     310.2\n167        75    120       150     320.4\n168        75    125       150     330.4'

In [56]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

In [57]:
import pandas as pd

df = pd.DataFrame(data)

df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

# Pandas - Analyzing DataFrames

Viewing the Data : use head() , this fn returns th header and a specified no of rows ,starting from top.

In [58]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.head(10))

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [59]:
import pandas as pd

df = pd.read_json('data.json')

print(df.head())

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

### There is also a tail() method for viewing the last rows of the DataFrame. The tail() method returns the headers and a specified number of rows, starting from the bottom.

In [60]:
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

### Info About the Data
The DataFrames object has a method called info(), that gives you more information about the data set.

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.6 KB